from database.models.university import University
from database.models.course import Course
from database.models.topic import Topic
from database.models.skill import Skill
from database.models.job import Job
from database.models.student import Student
from database.models.resource import Resource
from database.models.roadmap import Roadmap
from database.models.job_skill import JobSkill
from database.models.student_skill import StudentSkill